### ISSUE TITLE
Gshogi V 0.5.0, external engines

### ISSUE THREAD

**Issue by bewille** [johncheetham/gshogi#3]
Hi,
I am using Gshogi 0.45 and 0.50. With 0.5 external usi-engines do not run: the threads are started but do not receive usi-commands. Installed on Linux Mint 17.3 Python 3.4.3. Has somebody a hint?
Best regards 
Bernd Wille

**Comment by johncheetham** [comment]
Hi Bernd. Thanks for reporting this. I don't do much programming now but I managed to reproduce the error and believe I may have a solution. Can you try adding bufsize=1 to the subprocess.Popen command in usi.py. You will need to do this in 2 places (in start_engine and test_engine).

This worked for me using gse engine.

**Comment by bewille** [comment]
Hi John,
thanks for the quick reaction. Yes, this does the trick (tested with Laramie via wine and with gpsshogi).
I will add it to the pull-request.

**Comment by bewille** [comment]
Closed, see last mail
Hi John,
thanks for the quick reaction. Yes, this does the trick (tested with Laramie via wine and with gpsshogi).
I will add it to the pull-request.
