### ISSUE TITLE
Engine message

### ISSUE THREAD

**Issue by bewille** [johncheetham/gshogi#6]
Hi John,
I do not really want to mess with issues in the engine but I get this message about a position from a Meiji game where such a problem would not have gone undetected. Any hint where this message is generated? I could not find the strings in the engine sources.
Best regards 
Bernd
![screenshot from 2017-01-23 11 03 46](https://cloud.githubusercontent.com/assets/25171149/22203959/d0b16a70-e16f-11e6-96a8-33e1c046b329.png)

**Comment by johncheetham** [comment]
It's in psn.py load_game_psn_from_str method. It's split over more than 1 line so that might be why it's hard to find.

**Comment by bewille** [comment]
Hello John,
it's really my fault: the formatting of this .psn-File eliminated a "+" for promotion of a pawn going to 1a. Pawns going to the last row have to be promoted - the engine is right.
Sorry 
Bernd

P.S. I am about to fix a minor bug in handling of comments and will insert some more stuff for people who load games. To come in the next weeks.
